### ISSUE TITLE
Getting Issue when running RecLM-emb

### ISSUE THREAD

**Issue by DeepakJaiz** [microsoft/RecAI#54] opened 2024-07-10 10:16 UTC
When I am running the training command, bash shell/run_single_node.sh it create training.log file with failed  training and errors.

bash shell/run_single_node.sh
In this I get error i.e
1. tourch.dtype it want only from this option ["auto", "bfloat16", "float16", "float32"]. But in .sh file it is given as none for non llama model. SO I updated it as  "float32".
2. Here PEFT_MODEL_NAME=None is passed but when they read then it get None as string do condiion not worked, So I updated in file manually. In src/model.py line 54 I added this."peft_model_name=None"
3. Know I run this command in both gGPU macheiene and google colab but getting issue.

Error 1:   

Traceback (most recent call last):
  File "/home/ubuntu/RecLM-emb/train.py", line 131, in <module>
    main()
  File "/home/ubuntu/RecLM-emb/train.py", line 27, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/home/ubuntu/my_env/lib/python3.9/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 115, in __init__
  File "/home/ubuntu/my_env/lib/python3.9/site-packages/transformers/training_args.py", line 1372, in __post_init__
    and (self.device.type != "cuda")
  File "/home/ubuntu/my_env/lib/python3.9/site-packages/transformers/training_args.py", line 1795, in device
    return self._setup_devices
  File "/home/ubuntu/my_env/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/home/ubuntu/my_env/lib/python3.9/site-packages/transformers/training_args.py", line 1739, in _setup_devices
    self.distributed_state = PartialState(
  File "/home/ubuntu/my_env/lib/python3.9/site-packages/accelerate/state.py", line 230, in __init__
    torch.cuda.set_device(self.device)
  File "/home/ubuntu/my_env/lib/python3.9/site-packages/torch/cuda/__init__.py", line 326, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal

Error 2: 

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 27118) of binary: /home/ubuntu/my_env/bin/python3.9
Traceback (most recent call last):
  File "/home/ubuntu/my_env/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/my_env/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/my_env/lib/python3.9/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/ubuntu/my_env/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/ubuntu/my_env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/my_env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
To resolve this and testing I tried to pass only one file from all 10 file in traing, and also pass only 100 data of that file  to reduce the traing data but itsas not worked for me.

**Comment by Micheallei** [comment] 2024-07-11 03:28
Thank you for your feedback. 
1. We will update the run_single_node.sh script in the near future. 
2. For error 1: It should be caused by the inconsistency between the number of GPUs on your machine and the number in run_single_node.sh. Please set the value of `nproc_per_node` to the number of your GPUs.
3. For error 2: if you still encounter the problem after modifying `nproc_per_node`, please provide more detailed error information.

**Comment by Leavingseason** [comment] 2024-07-13 03:59
Updated and changes merged into main.

**Closed** 2024-07-22 03:42 UTC
